COSC481W-2021Fall/capstone-thriving-5

.gitignore
INSTALL

Details for installing Android, SQLite3, and Django REST Framework provided.

Fentry update install file

---

.idea/.gitignore
help-hero-front-end/app/src/main/java/com/example/helphero/SignUpActivity.java

I implemented error checking for input boxes. This will need to be updated once we discuss password requirements.

Error Checking for input boxes 

---

help-hero-front-end/app/src/main/java/com/example/helphero/SignUpActivity.java

Update SignUpActivity.java to require a specific password length and special character and numbers. Someone may need to check the regex.

Checks for password requirements

---

help-hero-front-end/app/src/main/java/com/example/helphero/SignUpActivity.java

Updated the error checking for the password and username.

Update Error Checking

---

help-hero-front-end/.idea/misc.xml
help-hero-front-end/app/src/main/java/com/example/helphero/HomeActivity.java
help-hero-front-end/app/src/main/res/layout/activity_home.xml
help-hero-front-end/app/src/main/res/layout/activity_sign_in.xml

Adding the ability to edit the check list, up to five items at a time, once the sixth item is entered a warning will tell teh user that it will overwrite the top value. any new tasks put in will default set to unchecked.

impl: Edit check List

---

help-hero-front-end/app/src/main/java/com/example/helphero/HomeActivity.java
help-hero-front-end/app/src/main/java/com/example/helphero/SignInActivity.java
help-hero-front-end/app/src/main/res/layout/activity_home.xml

Fixed a bug on the sign in page that was causing the app to crash and removed a line of code from HomeActivity.java that was causing errors. Issues #16 and #17

fix: fix bugs in sign in and home page

---

backend/HelpHeroServer/api/models.py

Created a table in the backend that will store tasks created by a user. Github issue #17

Impl: Add Task List Table

---

help-hero-front-end/.idea/deploymentTargetDropDown.xml
help-hero-front-end/.idea/gradle.xml
help-hero-front-end/app/src/main/res/layout/activity_home.xml

fix bugs with task bar not being in the right place so it wont show up on some devices

fix: Test branch

---

backend/HelpHeroServer/api/models.py
backend/HelpHeroServer/api/serializers.py
backend/HelpHeroServer/api/urls.py
backend/HelpHeroServer/api/views.py

- Created a function in the backend in views.py that allows users to edit their contact information and updates those changes in the database
- Added a new url in urls.py that handles requests for editing contact info and updating the database
- References Github issue #30

impl: Edit Contacts Backend

---

help-hero-front-end/.idea/misc.xml
help-hero-front-end/app/src/main/AndroidManifest.xml
help-hero-front-end/app/src/main/java/com/example/helphero/HomeActivity.java
help-hero-front-end/app/src/main/res/layout/activity_profile.xml

1. Created a plainview text box to display the username
2. Created a button to allow user to edit username call editUsername

impl: Added username display and edit username button

---

help-hero-front-end/app/build.gradle
help-hero-front-end/app/src/main/java/com/example/helphero/ProfileActivity.java
help-hero-front-end/app/src/main/res/layout/activity_profile.xml

-Updated activity_profile.xml adding cards with EditText boxes, edit buttons, checkboxes and a delete button so that the user can view their current contacts, edit, and delete them.
-Added a button for deleting the user's profile in activity_profile.xml in case the user would ever want to.
- Updated ProfileActivity.java, linking backend functions to the UI buttons.

impl: Added Contact List and Edit and Delete Buttons

---

backend/HelpHeroServer/api/models.py
backend/HelpHeroServer/api/serializers.py
backend/HelpHeroServer/api/urls.py
backend/HelpHeroServer/api/views.py

-adds delete user function
-adds change username function
-removes tasklist table

impl: Delete and edit user name functions Backend

---

backend/HelpHeroServer/api/models.py
backend/HelpHeroServer/api/serializers.py
backend/HelpHeroServer/api/urls.py
backend/HelpHeroServer/api/views.py
help-hero-front-end/.idea/misc.xml
help-hero-front-end/app/build.gradle
help-hero-front-end/app/src/main/AndroidManifest.xml
help-hero-front-end/app/src/main/java/com/example/helphero/HomeActivity.java
help-hero-front-end/app/src/main/java/com/example/helphero/ProfileActivity.java
help-hero-front-end/app/src/main/res/layout/activity_profile.xml

Merging this branch to main because all of issue #30 tasks are complete

impl: Profile page

---

help-hero-front-end/app/src/main/AndroidManifest.xml
help-hero-front-end/app/src/main/java/com/example/helphero/ProfileActivity.java
help-hero-front-end/app/src/main/java/com/example/helphero/SignInActivity.java
help-hero-front-end/app/src/main/java/com/example/helphero/SignUpActivity.java
help-hero-front-end/app/src/main/res/layout/activity_profile.xml

Issue #30 
- Saved username from the sign in and sign up pages to access in the profile page to display username and get corresponding contact info from database.
- Linked the edit username button to the backend functions to allow the user to change their username.
- Fixed the edit contact buttons on the profile page so that they properly send the changes to the backend database.

impl: Display/Change Username and Profile Page fixes

---

help-hero-front-end/app/src/main/AndroidManifest.xml
help-hero-front-end/app/src/main/java/com/example/helphero/ui/sos/SOSFragment.java
help-hero-front-end/app/src/main/res/layout/fragment_sos.xml

- Added a scroll view in fragment_sos.xml with contact cards with call buttons so that user can immediately call emergency contact.
- In SOSFragment.java, added code to retrieve the contacts and display the info on the cards. If a contact is empty, that card does not get displayed.
- In SOSFragment.java added function for when call buttons are clicked dial specified contact number in the android call app.
- Added phone permission in AndroidManifest.xml to allow autodialing
Issue #46

impl: Add Contact List and Call Buttons

---

help-hero-front-end/.idea/encodings.xml
help-hero-front-end/.idea/misc.xml
help-hero-front-end/app/src/main/java/com/example/helphero/Database.java
help-hero-front-end/app/src/main/java/com/example/helphero/TaskModel.java
help-hero-front-end/app/src/main/java/com/example/helphero/ui/home/HomeFragment.java
help-hero-front-end/app/src/main/res/layout/activity_main.xml
help-hero-front-end/app/src/main/res/layout/fragment_home.xml

- added the ability to save task list items after logging out
- added access to the internal database
- added taskModel.java and Database.java
- changed button text to "add task"
- changed the limit of tasks to unlimited as far as I am aware
- tapping on a task will delete the task instead of having checkboxes
- KNOWN BUG: logging in on a different account on the same device will load the database values
-for example, if I put "new task" in while on logged Brayden1 and
then logged out and logged in to Brayden2 it would still display
"new task" on the task list

impl: Task list update

---

backend/HelpHeroServer/api/models.py
backend/HelpHeroServer/api/serializers.py
backend/HelpHeroServer/api/urls.py
backend/HelpHeroServer/api/views.py

- Added createTasks, listTasks, and deleteTasks functions in views.py to store, retrieve, and delete user tasks in Backend
- Added new urls in urls.py for each of these functions to be used by the frontend
- Added a new serializer class in serializers.py for the task list
- Added a new table in models.py for storing user tasks
- Modified deleteUser function to delete all tasks associated with a deleted user
- Modified changeUsername function to update the value of task_creator with new username
References Github issue #48

impl: Store User Tasks in Backend

---

help-hero-front-end/.idea/misc.xml
help-hero-front-end/app/src/main/java/com/example/helphero/ui/sos/SOSFragment.java
help-hero-front-end/app/src/main/res/layout/fragment_sos.xml

1. Included a SOS text box to display the same PSA message to prevent self hamr
2. Added a button to Call 911
3. Upon clicking the button the users phone app will open so the user can click call and immediately call 911 in emergencies

impl: SOS text and Auto Dial 911

---

help-hero-front-end/app/src/main/java/com/example/helphero/Database.java
help-hero-front-end/app/src/main/java/com/example/helphero/ui/home/HomeFragment.java

- Task list is now updated in the backend when a user creates and deletes tasks locally
- Fixed a potential bug where the same tasks would appear for all users (further testing needed)
References Github issue #48

impl: Sync local with remote task list

---

help-hero-front-end/.idea/gradle.xml
help-hero-front-end/app/src/main/res/layout/fragment_sos.xml

- Fixed the constraints of fragment_sos.xml to make the sos page neater.
Issue #46

fix: SOS Page Layout
